name: update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: rake update
        env:
          NYT_S: ${{ secrets.NYT_S }}
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          if ! git diff-index --quiet HEAD data/**/*.json; then
            git add data/**/*.json
            git commit -m "`date -I`"
            git push
          fi
