name: update
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3
      - uses: actions/checkout@v2
      - run: rake update
        env:
          NYT_S: ${{ secrets.NYT_S }}
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "<>"
          if ! git diff-index --quiet HEAD --; then
            git add data/*.json
            git commit -m "`date -I`"
            git push
          fi
